# Generated by Django 4.2 on 2023-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
