# Generated by Django 4.2 on 2023-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_blog_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
