# Generated by Django 4.2 on 2023-05-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abouts',
        ),
    ]
